# Generated by Django 3.2 on 2021-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=20)),
                ('Action', models.CharField(max_length=10)),
            ],
        ),
    ]
