# Generated by Django 3.2 on 2021-04-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Action',
        ),
        migrations.AddField(
            model_name='login',
            name='Password',
            field=models.CharField(default='Manasa@123', max_length=20),
        ),
    ]
